***Mengyang Zheng HW 2 3/17/2021***

***Exercise 1: Data Description***
```{r}
rm(list=ls())
#install.packages("bayesm")
#install.packages("qwraps2")
library(bayesm)
marg=data(margarine)
price=margarine$choicePrice
demo=margarine$demos
all=merge(price,demo,by="hhid")
```

```{r}
#Average and dispersion in product characteristics
library(tidyr)
library(dplyr)
#Compute all summary statistics including both chosen products and non-chosen products
means <- t(all %>% summarise_at(3:12,mean))
mins <- t(all %>% summarise_at(3:12,min))
maxs <- t(all %>% summarise_at(3:12,max))
sds <- t(all %>% summarise_at(3:12,sd))
vars <- t(all %>% summarise_at(3:12,var))
des1=cbind(means,mins,maxs,sds,vars)
label1=c("mean","min","max","sd","var")
colnames(des1) <- label1
des1=round(des1,digits=3)
des1
```

```{r}
#Market share by product characteristics
#Find price for each choice
all$choiceprice=0
for (i in 1:nrow(all)){
  if (all$choice[i]==1){
  all$choiceprice[i]=all[i,3]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==2){
  all$choiceprice[i]=all[i,4]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==3){
  all$choiceprice[i]=all[i,5]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==4){
  all$choiceprice[i]=all[i,6]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==5){
  all$choiceprice[i]=all[i,7]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==6){
  all$choiceprice[i]=all[i,8]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==7){
  all$choiceprice[i]=all[i,9]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==8){
  all$choiceprice[i]=all[i,10]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==9){
  all$choiceprice[i]=all[i,11]
  }
}
for (i in 1:nrow(all)){
  if (all$choice[i]==10){
  all$choiceprice[i]=all[i,12]
  }
}

#compute market share by unit and market share below/above average
des2= all %>%
  group_by(choice) %>%
  summarize(
    totalunit=n()
  ) %>%
  mutate(
    unitshare=totalunit/sum(totalunit)
  ) 

desx= all %>%
  group_by(choice) %>%
  summarize(
    unitbelow=sum(choiceprice<=mean(choiceprice)),
    unitabove=sum(choiceprice>mean(choiceprice))
  ) %>%
  mutate(
    belowshare=unitbelow/sum(unitbelow),
    aboveshare=unitabove/sum(unitabove)
  )
desx
label2=colnames(all[3:12])
des2=round(des2,digits=3)
des2$choice[1:10]=label2[1:10]
desx=round(desx,digits=3)

des2=cbind(des2,desx[2:5])
des2
```


```{r}
#Illustrate mapping between observed attributes and choices
#Ultimately we try to find most preferred choice for all dummy attributes from demo
des3= all %>%
  group_by(choice) %>%
  summarize(
    famsize1_2=sum(Fs3_4 == 0 & Fs5.==0),
    famsize3_4=sum(Fs3_4 == 1 & Fs5.==0),
    famsize5.=sum(Fs3_4 == 0 & Fs5.==1),
    college=sum(college==1),
    whtcollar=sum(whtcollar==1),
    retired=sum(retired==1)
  )
notdes3= all %>%
  group_by(choice) %>%
  summarize(
    notcollege=sum(college==0),
    notwhtcollar=sum(whtcollar==0),
    notretired=sum(retired==0)
  )
des3=merge(des3,notdes3)
des3$choice[1:10]=label2[1:10]
des3

#As we can see from table below, all attributes tend to choose Pk_Stk as first choice and then choose BB_Stk as 2nd choice except for those family size over 5 who tend to choose Hse_Stk as 2nd choice.

#This is pretty much meaningless so we can compute the market share for each attribute and see the comparison difference.
des3share= des3 %>%
  summarize(
    famsize1_2=des3[1:10,2]/sum(famsize1_2),
    famsize3_4=des3[1:10,3]/sum(famsize3_4),
    famsize5.=des3[1:10,4]/sum(famsize5.),
    college=des3[1:10,5]/sum(college),
    whtcollar=des3[1:10,6]/sum(whtcollar),
    retired=des3[1:10,7]/sum(retired),
    notcollege=des3[1:10,8]/sum(notcollege),
    notwhtcollar=des3[1:10,9]/sum(notwhtcollar),
    notretired=des3[1:10,10]/sum(notretired)
  )
des3share=round(des3share,digits=3)
choice=label2[1:10]
des3share=cbind(choice,des3share)
des3share
#As we can see from the share table，we can see the share change across different attributes. Bigger family size tend to have bigger share in Hse_Stk and Gen_Stk. No big difference between shares of college or not college and whitecollar or not whitecollar. However, for retired and non-retired group, nonretired group tend to buy more of Pk_Stk and Hse_Stk.

```

***Exercise 2: First Model***

```{r}
#The first model we would use conditional logit since price does not vary across different households.
library(mlogit)
library(stargazer)
library(texreg)
library(survival)
library(nnet)
library(stringr)

#Use mlogit package to compute the coefficients
price=margarine$choicePrice
colnames(price)[3:12]=str_c("price",1:10)
clogit0=mlogit.data(price,varying=3:12,shape="wide",sep="",choice="choice")
clogit1=mlogit(choice~price,data=clogit0)
summary(clogit1)
```

```{r}
#Write the likelihood for conditional logit and optimize the model

#reference: https://stats.stackexchange.com/questions/389758/conditional-logistic-regression-in-r

ni=nrow(price)
nj=ncol(price[,3:12])

#First we introduce a choice matrix where for individual i, if product j is chosen then cm[i,j]=1
cm=matrix(0,ni,nj)

for (i in 1:ni){
  if (price[i,2]==1){
    cm[i,1]=1
  } else if (price[i,2]==2){
    cm[i,2]=1
  } else if (price[i,2]==3){
    cm[i,3]=1
  } else if (price[i,2]==4){
    cm[i,4]=1
  } else if (price[i,2]==5){
    cm[i,5]=1
  } else if (price[i,2]==6){
    cm[i,6]=1
  } else if (price[i,2]==7){
    cm[i,7]=1
  } else if (price[i,2]==8){
    cm[i,8]=1
  } else if (price[i,2]==9){
    cm[i,9]=1
  } else if (price[i,2]==10){
    cm[i,10]=1
  } 
}


clogit_ll<-function(beta){
  
  #Adding 0 as the base coefficient(whenever cbind with 0 it means adding the base coefficient in it)
  b1=cbind(0,matrix(rep(beta[1:(nj-1)],each=ni),ni,nj-1))
  
  #Use the lecture definition of conditional logit to compute the likelihood
  XB=price[,3:12]*beta[nj]
  XB=b1+XB
  eXB=exp(XB)
  teXB=rowSums(eXB)
  prob=eXB/teXB
  
  #Compute the neg log likelihood for each choice using the choice matrix
  llik=sum(cm*log(prob))
  return(-llik)
}

set.seed(0)
model1 <- optim(runif(10,-0.1,0.1),clogit_ll,method="BFGS")
model1$par

```

```{r}
#Same result as the package result so it should be correct. The interpretation of the coefficient (-6.656) is that price is negatively related to demand. If price is high, then the product will be less likely to get purchased. 
```

***Exercise 3: Second Model***
```{r}
#Now we can use our all data, which is the merge of choicePrice and demos.

#The second model should be the multinomial logit model since income varies across different household id.

#Use the mlogit package to test again.
colnames(all)[3:12]=str_c("price",1:10)
mlogit0=mlogit.data(all,varying=3:12,shape="wide",sep="",choice="choice")
mlogit1=mlogit(choice~0 | Income,data=mlogit0)
summary(mlogit1)
```

```{r}
#Write the likelihood and optimize the model
mlogit_ll <- function(beta){
  
  #We now have 2 sets of coefficients, same adding 0 as the base coefficient
  b1=cbind(0,matrix(rep(beta[1:(nj-1)],each=ni),ni,nj-1))
  b2=cbind(0,matrix(rep(beta[nj:(2*(nj-1))],each=ni),ni,nj-1))
  
  #Since income is for each household, so same for all choices on household level
  XB=b1+b2*cbind(all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13])
  
  #Same calculation process as model1
  eXB=exp(XB)
  teXB=rowSums(eXB)
  prob=eXB/teXB
  llik=sum(cm*log(prob))
  return(-llik)
}

set.seed(0)
model2 <- optim(runif(18,-0.1,0.1),mlogit_ll,method="BFGS")
model2$par[1:18]
```

```{r}
#The result from second model is very close to the result from the package one. A higher income will have a better likelihood to purchase product 3,4,6,8,9,10 and less likely to purchase product 2,5,7 in comparison to the likelihood of product 1 (the product number is in the order of the column names).
```

***Exercise 4: Marginal Effects***
```{r}
#Marginal effect of the first model by package
effects(clogit1,covariate="price")
```

```{r}
#The result of marginal effect of the first model is a 10 by 10 matrix

b=as.matrix(c(0,model1$par[1:9]))
me1=matrix(0,10,10)
for (i in 1:ni){
  eXB1=as.matrix(exp(price[i,3:12]*model1$par[10]+b))
  teXB1=rowSums(eXB1)
  prob1=eXB1/teXB1
  df=matrix(0,10,10)
  indicator=diag(1,10,10)
  for (m in 1:10){
    indicator[,m]=indicator[,m]-prob1
  }
  for (n in 1:10){
    df[n,]=indicator[n,]*model1$par[10]*prob1
  }
  
  me1=me1+df
}

me1/ni
#Close to our package marginal effect result

#So from marginal effect we can tell that in comparison, purchasing more of any product will increase the probability of purchasing all other products and decrease the probability of buying itself again (Marginal diminishing law?).
```

```{r}
#Marginal effect of the second model by package
effects(mlogit1,covariate="Income")
```

```{r}
#Now we want to compute the marginal effect for the second model without package use
b1=c(0,model2$par[1:9])
b2=c(0,model2$par[10:18])
me2=matrix(0,1,nj)
for (i in 1:ni){
  eXB2=exp(b1+b2*cbind(all[i,13],all[i,13],all[i,13],all[i,13],all[i,13],all[i,13],all[i,13],all[i,13],all[i,13],all[i,13]))
  teXB2=rowSums(eXB2)
  prob2=eXB2/teXB2
  me2=me2+prob2*(b2-rowSums(b2*prob2))
}
me2/ni
#Confirmed they have very close estimation.
#I believe increasing in income would not influence the chances of buying different choices by much since all the coefficient are pretty small and income does not have a large unit (ranged from 7.5 to 130).
```


***Exercise 5: IIA***
```{r}
#Use package to check the coefficients before we remove one choice
mxlogit1=mlogit(choice~price|Income,data=mlogit0)
summary(mlogit1)
```
```{r}
#Now we remove one choice from our data and rerun everything

all2=all
all2=all2[all2$choice !=10,]
mxlogit0=mlogit.data(all2,varying=3:11,shape="wide",sep="",choice="choice")
mxlogit2=mlogit(choice~price|Income,data=mxlogit0)
summary(mxlogit2)
```
```{r}
#According to the package IIA property has been rejected if we remove choice 10
hmftest(mxlogit1,mxlogit2)
```

```{r}
mxlogit_ll <- function(beta){
  
  b1=cbind(0,matrix(rep(beta[1:(nj-1)],each=ni),ni,nj-1))
  b2=cbind(0,matrix(rep(beta[(nj+1):(2*nj-1)],each=ni),ni,nj-1))

  #Term of XB+WGamma on the slide
  XB=price[,3:12]*beta[nj]+b1+b2*cbind(all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13],all[,13])+b1
  eXB=exp(XB)
  teXB=rowSums(eXB)
  prob=eXB/teXB
  llik=sum(cm*log(prob))
  return(-llik)
}

set.seed(0)
model3=optim(runif(19,-0.1,0.1),mxlogit_ll)
bf=model3$par
bf
```

```{r}
#Since we drop choice 10 we need to re-construct the choice matrix without tenth column
cm2=matrix(0,ni,nj-1)

for (i in 1:ni){
  if (price[i,2]==1){
    cm2[i,1]=1
  } else if (price[i,2]==2){
    cm2[i,2]=1
  } else if (price[i,2]==3){
    cm2[i,3]=1
  } else if (price[i,2]==4){
    cm2[i,4]=1
  } else if (price[i,2]==5){
    cm2[i,5]=1
  } else if (price[i,2]==6){
    cm2[i,6]=1
  } else if (price[i,2]==7){
    cm2[i,7]=1
  } else if (price[i,2]==8){
    cm2[i,8]=1
  } else if (price[i,2]==9){
    cm2[i,9]=1
  } 
}

cm2=cm2[!(cm2[,1]==0 & cm2[,2]==0 & cm2[,3]==0 & cm2[,4]==0 & cm2[,5]==0 & cm2[,6]==0 & cm2[,7]==0 & cm2[,8]==0 & cm2[,9]==0) ,]

#Then basically repeat what we did before
mxlogit_ll2 <- function(beta){
  ni=nrow(all2) 
  b1=cbind(0,matrix(rep(beta[1:(nj-2)],each=ni),ni,nj-1))
  b2=cbind(0,matrix(rep(beta[nj:(nj+7)],each=ni),ni,nj-1))
  
  #Term of XB+WGamma on the slide
  XB=price[,3:11]*beta[nj-1]+b1+b2*cbind(all2[,13],all2[,13],all2[,13],all2[,13],all2[,13],all2[,13],all2[,13],all2[,13],all2[,13],all2[,13])+b1
  eXB=exp(XB)
  teXB=rowSums(eXB)
  prob=eXB/teXB
  llik=sum(cm2*log(prob))
  return(-llik)
}

set.seed(0)
model4=optim(runif(17,-0.1,0.1),mxlogit_ll2)
br=model4$par
br
```

```{r}
#Reshape the full model coefficients so bf and br have the same length
bf=bf[c(1:8,10:18)]

#Compute the test statistics
MTT=c(0,-2*(bf-br))
chisq.test(abs(MTT))

#So we reject the IIA property as p-value is equal to 1. (I understand my results are different from the package results. I think this happens mostly because I somehow did not write correct mixed logit formula. I do not know how to correct my answer. But for the rest of the parts should be correct including building the specification model with 1 less choice.)
```